### ISSUE TITLE
Fehlercode/Return-Value

### ISSUE THREAD

**Issue by nils-tekampe** [konfidas/TTC#25]
Ich überlege, TTC als Kommandozeilentool einen vernünftigen Return-Value zu verpassen.
Ich stelle mir vor:
0: Alles OK
-1: Es wurden einzelne Fehler festgestellt aber es konnte einmal komplett geparst weren
-2: Schwerwiegende Fehler. Das Parsen wurde unterbrochen (z.B. IOFehler und Co). 

@dheldt  Was meinst Du?

**Comment by dheldt** [comment]
Hi, 

From my perspective it doesn't matter. I guess we will write some Reporter, that creates an HTML report, which contains all details/problems and gives additional insight into the TAR. From my perspective, the commandline interface will not carry far, so I do not care :) 

do as you like.

**Comment by nils-tekampe** [comment]
Thanks!
