### ISSUE TITLE
Language of the code

### ISSUE THREAD

**Issue by dheldt** [konfidas/TTC#34]
I noticed, that you write English function / variable names, but commit messages and comments are in German.

Is this intentionally?

**Comment by nils-tekampe** [comment]
I am somehow undecided (obviously). As the tool is only directed to the German market I guess that german should be the language of choice.

**Comment by dheldt** [comment]
Well, I heard that even in German Companies, there are fellows not being able to speak German... Anyway, 

This means I will write comments in German, when feasible.
