### ISSUE TITLE
Creating DataToBeSigned fails, when some LogMessageElements contain extended Length Data

### ISSUE THREAD

**Issue by dheldt** [konfidas/TTC#4]
The assembly of DTBS (DataToBeSigned) during the parsing of the log message uses statements like

`  byte[] elementValue = Arrays.copyOfRange(element.getEncoded(), 2, element.getEncoded().length);`

These fail, when the ASN1 Element in Question has a length, that requires ExentedeLengthEncoding. 

This is not top priority right now, but has to be fixed at some point in time.

**Comment by nils-tekampe** [comment]
Erledigt
